### PR TITLE
LJ Validation Workflow

### PR DESCRIPTION
**Pull request by tommy-waltmann**
## Description

Adds a workflow to validate LJ Fluid behavior. The workflow runs simulations in NVT in both MC and MD in order to compute the pressure (and compare values), which are then used to run simulations in NPT in both MC and MD.

It then computes the density of the systems in NPT in order to compare back to the original density of the NVT simulations.

Pressures are computed by hand for MC simulations by explicit evaluation of the virial.

## Motivation and context

This will be the first major workflow added to this repository.

## How has this been tested?

This PR is still a draft, and running the whole workflow on a cluster to verify correctness has not yet been done.

## Checklist:

- [ ] I have reviewed the [**Contributor Guidelines**](https://github.com/glotzerlab/hoomd-validation/blob/trunk/CONTRIBUTING.md).
- [ ] I agree with the terms of the [**HOOMD-blue Contributor Agreement**](https://github.com/glotzerlab/hoomd-validation/blob/trunk/ContributorAgreement.md).
- [ ] My name is on the list of contributors (`CONTRIBUTORS.md`) in the pull request source branch.

### CODE REVIEW

**Review by joaander — CHANGES_REQUESTED** [review]
Thanks! I suggest changes to clean up the code, fix the XPLOR smoothing in MD simulations, and make the code more configurable for other users.

**Review by b-butler — CHANGES_REQUESTED** [review]
Thanks for the work @tommy-waltmann. I tried to leave some helpful comments regarding modularity and some refactoring. I don't want the perfect to be the enemy of the good here though, so if I am being too ambitious we can discuss what are must haves for the PR.

**Review by b-butler — CHANGES_REQUESTED** [review]
This is looking better. I have a few more simplifying comments to address.

**Review by joaander — CHANGES_REQUESTED** [review]
Thanks! Let's see if one final round of tweaks gets all the modes in agreement.

**Review by joaander — COMMENTED** [review]
Some small comments to take care of eventually. 

I'm making some other changes directly, hoping to get the simulation modes to match better.

**Review by joaander — COMMENTED** [review]
Output from the latest run:
plots
compare_kT1 25_density0 05

I made a lot of changes to the simulation protocol, but the main ones that led to passing tests were:
* Decreasing dt for MD - dt=0.005 introduce measurable (many sigma) differences between MD and MC.
* Running short simulations targeting 1e-3 relative error - longer simulations reduce the relative error to 1e-5, but somehow individual simulation modes get correlated errors that shift their averages up or down (randomly depending on the sate point) by 1e-4.
* Using NPT MC as the reference simulation and setting the density of the others to match - the pressure measurement in MD is too noisy to give a good read on the average pressure (also, see point 2).

I have a few signac questions in this review. I also plan to add GPU simulation runs into the comparison mix before calling this one done.

**Review by joaander — COMMENTED** [review]
I think this is good to go now. @tommy-waltmann, would you like to comment on any of the changes I made?

**Review by joaander — APPROVED** [review]

**Review by tommy-waltmann — COMMENTED** [review]
Just a few quick questions. Overall, the workflow is much improved and its great that this is almost ready to go.

**Review by b-butler — COMMENTED** [review]
There are no big changes I suggested, but various clean ups and such.

**Review by b-butler — COMMENTED** [review]
I made a couple comments and moved some of the plotting logic into functions (within the operation). The PR should be ready after these minor changes.

**Review by joaander — CHANGES_REQUESTED** [review]
The rewritten plotting code must be tested before we merge. I'm rerunning the workflow now.

**Review by joaander — CHANGES_REQUESTED** [review]

**Review by joaander — APPROVED** [review]
Thanks!

**Review by b-butler — APPROVED** [review]

**Pull request merged**
